name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: open-skill-nepal-478611
  SERVICE: open-skill-nepal
  REGION: asia-south1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        source: ./backend
        flags: "--allow-unauthenticated --port=8080 --set-env-vars=NODE_ENV=production"
